version: "3"
services:
  db_auth:
    restart: always
    container_name: db_transactions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.16
    # volumes:
    #   - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./postgres/data:/var/lib/postgresql/data

  flask-service:
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=7100
      - FLASK_APP=hello.py
    build:
      context: "."
      dockerfile: "./flask1/DockerfileFlask"
    depends_on:
      - db_auth
    expose:
     - "7100"
    ports:
      - "7100:7100"
    volumes:
      - ./flask1:/opt/app